"""Initial migration

Revision ID: 09675a91ba0d
Revises: 8b64b9877cb2
Create Date: 2026-06-07 19:13:57.484634

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "09675a91ba0d"
down_revision: str | Sequence[str] | None = "8b64b9877cb2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
