import type { CommentaryResponse } from "@shared/types";

export const DEMO_DATA: CommentaryResponse = {
    board_size: 19,
    sgf_file_name: "demo.sgf",
    language: "english",
    moves: [
        ["B", [15, 15]],
        ["W", [3, 3]],
        ["B", [15, 2]],
        ["W", [3, 16]],
        ["B", [3, 14]],
        ["W", [2, 14]],
        ["B", [2, 13]],
        ["W", [2, 15]],
        ["B", [5, 2]],
        ["W", [2, 5]],
        ["B", [3, 12]],
        ["W", [4, 15]],
        ["B", [2, 8]],
        ["W", [16, 4]],
        ["B", [15, 7]],
        ["W", [12, 2]],
        ["B", [15, 4]],
        ["W", [9, 2]],
        ["B", [16, 3]],
        ["W", [3, 1]],
        ["B", [16, 13]],
        ["W", [10, 16]],
        ["B", [3, 4]],
        ["W", [4, 4]],
        ["B", [8, 3]],
        ["W", [3, 5]],
        ["B", [8, 2]],
        ["W", [9, 3]],
        ["B", [9, 4]],
        ["W", [10, 4]],
        ["B", [10, 5]],
        ["W", [11, 4]],
        ["B", [11, 5]],
        ["W", [9, 1]],
        ["B", [8, 5]],
        ["W", [12, 5]],
        ["B", [12, 6]],
        ["W", [13, 5]],
        ["B", [13, 6]],
        ["W", [16, 12]],
        ["B", [15, 12]],
        ["W", [16, 11]],
        ["B", [17, 13]],
        ["W", [15, 8]],
        ["B", [16, 7]],
        ["W", [12, 9]],
        ["B", [9, 15]],
        ["W", [10, 15]],
        ["B", [9, 14]],
        ["W", [10, 14]],
        ["B", [10, 13]],
        ["W", [11, 13]],
        ["B", [11, 12]],
        ["W", [12, 13]],
        ["B", [12, 12]],
        ["W", [10, 12]],
        ["B", [9, 13]],
        ["W", [13, 12]],
        ["B", [10, 11]],
        ["W", [14, 13]],
        ["B", [15, 13]],
        ["W", [9, 12]],
        ["B", [13, 11]],
        ["W", [8, 12]],
        ["B", [14, 12]],
        ["W", [13, 13]],
        ["B", [11, 11]],
        ["W", [9, 16]],
        ["B", [8, 10]],
        ["W", [8, 8]],
        ["B", [10, 9]],
        ["W", [11, 6]],
        ["B", [9, 7]],
        ["W", [14, 6]],
        ["B", [14, 7]],
        ["W", [15, 5]],
        ["B", [16, 5]],
        ["W", [10, 10]],
        ["B", [9, 9]],
        ["W", [9, 11]],
        ["B", [11, 10]],
        ["W", [11, 9]],
        ["B", [7, 12]],
        ["W", [8, 13]],
        ["B", [7, 14]],
        ["W", [8, 14]],
        ["B", [8, 15]],
        ["W", [7, 15]],
        ["B", [8, 16]],
        ["W", [7, 13]],
        ["B", [9, 10]],
        ["W", [10, 8]],
        ["B", [8, 17]],
        ["W", [6, 14]],
        ["B", [12, 15]],
        ["W", [7, 16]],
        ["B", [3, 2]],
        ["W", [4, 2]],
        ["B", [14, 14]],
        ["W", [7, 17]],
        ["B", [8, 18]],
        ["W", [9, 17]],
        ["B", [12, 7]],
        ["W", [9, 8]],
        ["B", [6, 10]],
        ["W", [10, 6]],
        ["B", [9, 5]],
        ["W", [7, 9]],
        ["B", [7, 10]],
        ["W", [7, 6]],
        ["B", [7, 5]],
        ["W", [6, 6]],
        ["B", [11, 2]],
        ["W", [14, 4]],
        ["B", [17, 4]],
        ["W", [12, 1]],
        ["B", [12, 3]],
        ["W", [12, 4]],
        ["B", [5, 4]],
        ["W", [4, 5]],
        ["B", [13, 3]],
        ["W", [11, 3]],
        ["B", [6, 8]],
        ["W", [8, 7]],
        ["B", [5, 1]],
        ["W", [13, 8]],
        ["B", [15, 6]],
        ["W", [14, 5]],
        ["B", [13, 7]],
        ["W", [11, 8]],
        ["B", [11, 1]],
        ["W", [10, 2]],
        ["B", [4, 7]],
        ["W", [4, 6]],
        ["B", [1, 14]],
        ["W", [12, 17]],
        ["B", [5, 3]],
        ["W", [2, 2]],
        ["B", [1, 15]],
        ["W", [1, 16]],
        ["B", [13, 17]],
        ["W", [12, 16]],
        ["B", [13, 16]],
        ["W", [16, 9]],
        ["B", [1, 6]],
        ["W", [13, 18]],
        ["B", [14, 18]],
        ["W", [12, 18]],
        ["B", [15, 17]],
        ["W", [7, 1]],
        ["B", [8, 1]],
        ["W", [8, 0]],
        ["B", [7, 2]],
        ["W", [5, 7]],
        ["B", [5, 8]],
        ["W", [3, 7]],
        ["B", [1, 5]],
        ["W", [1, 4]],
        ["B", [0, 4]],
        ["W", [0, 3]],
        ["B", [11, 0]],
        ["W", [10, 0]],
        ["B", [15, 10]],
        ["W", [14, 8]],
        ["B", [16, 10]],
        ["W", [17, 10]],
        ["B", [8, 6]],
        ["W", [17, 8]],
        ["B", [11, 16]],
        ["W", [11, 17]],
        ["B", [0, 16]],
        ["W", [0, 17]],
        ["B", [11, 14]],
        ["W", [7, 18]],
        ["B", [13, 14]],
        ["W", [9, 18]],
        ["B", [10, 13]],
        ["W", [9, 13]],
        ["B", [4, 14]],
        ["W", [3, 9]],
    ],
    initial_stones: [],
    comments: [
        {
            turn: 12,
            winrate_delta: 6.5,
            color: null,
            comment:
                "At move 12, White trails by about one point with only 36.5% winning chances, so White needs to improve the position decisively. Q5 is a practical move that gains ground in the lower-right corner where White's stones already have some presence, and it does modestly help White's position — the winrate improves by 6.5 points and the score deficit shrinks by 0.6 points. However, this move fell outside KataGo's analyzed candidate set, suggesting it is not optimal for this position.\n\nThe suggested alternative, R17, is dramatically stronger: it would have given Black a 63.9% win probability and a +1.1 point lead, versus the 43.0% Black gets after Q5 — a swing of over 20 percentage points. Looking at the board, R17 attacks the upper-right corner where Black has already established stones at P16 and C16, and the principal variation shows the resulting fight developing along the right edge (R17, Q17, R16, R14, R15, Q15, S14) before shifting toward the center and left side. The ownership map shows the upper-right is still partially contested, whereas Q5 placed White in an area already leaning White; R17 appears to target more valuable, contested territory and seize the initiative in a critical area.",
        },
        {
            turn: 18,
            winrate_delta: 4.2,
            color: null,
            comment:
                "# Commentary: White's Move 18 (C10)\n\nThe game remains tightly balanced after Black's 17th move—White holds a slender 0.5-point lead with 42.6% Black win probability, and the left and upper sides are still largely unsettled. White's play at C10 is a modest move that improves the position locally: it gains 4.2% win probability and recovers 0.4 points, but KataGo ranks it only 5th best and assigns it a very low neural prior (0.006), suggesting this defensive region did not naturally demand attention. \n\nKataGo's top choice was D17, a point higher and well into Black's stronger area on the upper-left (the ownership map shows Black holding 0.6+ ownership at D17–D18). D17 would have pushed Black's win probability to 58% and secured a +0.6 point lead; the principal variation traces through a large-scale fight around rows 16–18 and then pivots down to contested space near C9, B5, and the bottom-left corner. The data suggest D17 seized the upper-left's potential more actively, whereas C10, though solid, left that rich territory untouched.",
        },
        {
            turn: 24,
            winrate_delta: 0.5,
            color: null,
            comment:
                "# Commentary: White's move 24 (E5)\n\nThe game remains tightly balanced at this stage, with Black clinging to a minimal +0.2 point lead and essentially even winning chances (50.4%). White's move at E5 is an excellent choice—it ranks first in KataGo's evaluation with a high policy prior of 0.234, indicating it looks natural and strong to the engine's eye. The move slightly improves White's position, reducing Black's winning chances by half a percent and keeping the score essentially tied.\n\nLooking at the board, E5 sits at the boundary of the lower-left region, where White already commands meaningful territory (around C4–D4, with the ownership map showing that area leans White by roughly 19 points net). E5 appears to reinforce that region while simultaneously pressing into the slightly contested area around D–E columns in rows 5–9. The principal variation that follows—D9, F4, C9, and a sequence running along the left side—suggests White is building coherent influence and territory there; however, the exact tactical justification for why this particular move is optimal rather than an alternative joseki or approach move is difficult to pin down from the position alone.",
        },
        {
            turn: 25,
            winrate_delta: 0.6,
            color: null,
            comment:
                "The game remains essentially equal at move 25, with Black holding a razor-thin +0.3 point lead and 50% win probability—any mistake could swing the balance. Black's D9 is a solid, second-best choice that improves the position slightly (+0.6% win rate), but it ranks as the neural net's lower-priority move (policy prior only 0.049), suggesting it wasn't the most natural-looking response. KataGo's top pick, D10, offers a cleaner continuation: it gains +0.7% win rate over D9 and the principal variation (D10–C9–C11–B11–D11–B12...) shows Black pressing along the left side, where the board is still contested and every stone matters. The exact tactical refinement D10 provides is difficult to pin down from this position alone, but the move sets up tighter control in the left side cluster around C–D columns, where both players' stones are concentrated.",
        },
        {
            turn: 30,
            winrate_delta: -7.1,
            color: null,
            comment:
                "# Commentary: White's Move 30 (E11)\n\nThe game was tightly balanced before this move—Black held just a 0.2-point lead with 49.5% win probability, suggesting nearly even chances. White played E11, but this was only KataGo's 5th-choice move; the engine shifted the evaluation sharply against White, dropping Black's win rate by 7.1 percentage points and improving Black's score lead to +0.9 points. KataGo's top recommendation was M3, which would have kept the position much closer to even (Black at 51.8%, score near 0.0), avoiding the immediate deterioration that E11 allowed.\n\nLooking at the board and ownership map, the left side remains contested, and E11 does not clearly advance White's position there. The principal variation after M3 suggests White should have focused on the lower side and corners (the sequence runs M3–P2–B9–B8, etc.), where White's existing strength around F3–Q4 is more naturally deployed. E11 appears to have been a passive, slow move in a position where White needed more forcing play to maintain balance.",
        },
        {
            turn: 40,
            winrate_delta: -8.4,
            color: null,
            comment:
                "# Move 40 Commentary: White N17\n\nAt this point the game remains close, with Black holding a modest +0.7 point lead and 54% win probability after move 39. White's play at N17 significantly worsened the position: it was only KataGo's 11th choice with an extremely low policy prior (0.006), and it immediately cost White +8.4% win probability, pushing Black's lead to +1.5 points. The upper-right corner where N17 was placed is contested territory leaning toward Black (local ownership ~+0.47), making it a poor place for White to invest.\n\nInstead, KataGo's top choice M3 targets the lower edge, where White has the advantage—the ownership map shows White's strongest region lies around F3 with roughly +19 points of control, and the lower-left is still partially undecided. The principal variation through M3 unfolds along the right and bottom edges (M3 → P2 → K4 → Q10, etc.), suggesting this move aims to activate White's lower-side potential and contest the right side before Black consolidates there. By playing M3, White would have flipped the board to a small lead (−0.6 points, 46.9% Black win probability)—a swing of 9 percentage points in a single move.",
        },
        {
            turn: 42,
            winrate_delta: -5.0,
            color: null,
            comment:
                "# Commentary on White M17\n\nWhite enters move 42 in a difficult position: Black has built a +1.5 point lead with 61.4% winning chances, and White needs to regain momentum. M17, however, worsens the situation—KataGo ranks it only 3rd best, and playing it swings the evaluation against White by a full 5%, pushing Black's win rate to 66.4% and extending the lead to +2.0 points. The move is placed in the upper side where the ownership map shows Black leaning (+0.30 locally), so White is playing into Black's strength rather than contesting contested or White-friendly territory.\n\nKataGo's top choice, M3, tells a starkly different story. Playing there would shift Black's winning chances down to 39.7% and flip the score to White +1.4—a swing of more than 7 points in one move. The principal variation shows the fight shifting to both the lower and upper sides (M3 → N2 → K4 → J4 → M16 → M17...), suggesting M3 initiates a forcing sequence that disrupts Black's plans and gives White better practical chances where the board is still contested. While the exact tactical sequence is complex, the data makes clear that White chose a passive move in a spot where the game demanded urgency.",
        },
        {
            turn: 43,
            winrate_delta: -1.0,
            color: null,
            comment:
                "# Commentary on Black Move 43 (O18)\n\nBlack enters this position with a solid but narrow advantage: a +1.9 point lead and 65.7% win probability. O18 is an excellent choice here — it ranks as KataGo's top suggestion with a strong policy prior (0.835), indicating it's a natural, forcing move. After O18, Black's winrate ticks up to 64.7% (a modest -1.0% swing), but the position remains strategically sound at +1.9 points.\n\nThe appeal of O18 becomes clearer in the ownership map and the principal variation: the move extends Black's influence into the upper-right corner and along row 18, where local ownership strongly favors Black (average ~+0.56). The 12-move sequence that follows (M3, P2, K4, Q10, Q11, P10, R15, R16, P11, O10) suggests KataGo sees a concrete plan to solidify the right side and capitalize on the corner—territory where Black is already leading in the local fight. While the exact tactical payoff of this sequence is difficult to pin down from the position alone, the move efficiently consolidates Black's existing strength in a region where the outcome is still being decided.",
        },
        {
            turn: 44,
            winrate_delta: -10.4,
            color: null,
            comment:
                "White was already in trouble—Black held a 65% win probability and a nearly 2-point lead—and J16 made the situation significantly worse. This move, ranked only 12th by KataGo (with a policy prior of 0.007), handed Black an additional 10.4 percentage points of winning chances and cost White over a point in expected score. The ownership map shows J16 was placed in contested territory that locally favors Black, and it doesn't appear to accomplish a clear purpose in either attacking Black's upper-right cluster or securing White's own walls.\n\nKataGo's top choice, M3, would have pivoted the game entirely: it swings the evaluation by nearly 11 percentage points in White's favor, converting the position from a losing one (+3.1 pts for Black) to roughly even (-1.8 pts, favoring White). The principal variation threading through P2, K4, and the right side suggests M3 targets the lower-right region, where White has scattered stones (Q4, O3, P5) and Black's position is less cohesive—essentially fighting for control of an area that remains largely undecided rather than entering a zone where Black already enjoys strong influence.",
        },
        {
            turn: 58,
            winrate_delta: null,
            color: null,
            comment:
                "With move 58, White remains in a difficult position: Black maintains an 83.6% win probability and leads by approximately 5 points, a substantial margin at this stage. White's move to N14 is well-chosen—KataGo ranks it as the top move with a high policy prior of 0.839, indicating it is a natural and forceful continuation. The move makes minimal immediate gain in absolute terms (Black's lead shrinks by just 0.1 points), but it engages Black's stones in the upper-right region, where the ownership map shows genuine contestation; the principal variation that follows (N14 → M11 → N15 → M16 → N10, etc.) suggests White is probing for tactical opportunities and attempting to create complications in an area where Black has not yet secured clear control.",
        },
        {
            turn: 79,
            winrate_delta: -2.8,
            color: null,
            comment:
                "Black is in a commanding position, leading by nearly 14 points with a 96% win probability—this is essentially a won game. K10 is a reasonable move that maintains Black's advantage, but it represents a step backward: it drops Black's winrate by 2.8% and the score lead by 3.6 points, placing it only 5th among KataGo's candidate moves. The move appears to make solid contact in the center where Black already owns significant territory, but it allows White unnecessary counterplay.\n\nL10, just one space to the right, would have been notably stronger—it preserves Black's 97% winrate and extends the score lead to +14.7 points instead of +10.3. The principal variation following L10 runs deep through the center and upper side (G11, F10, J11, and beyond), suggesting it creates more efficient threats and tighter control of the contested middle zone, where the ownership map shows several \"?\" squares that L10 apparently resolves in Black's favor more cleanly than K10 does. Since Black is already winning decisively, the tighter, more forcing sequence L10 offers would have been the precise way to convert this advantage without allowing White any tactical breathing room.",
        },
        {
            turn: 85,
            winrate_delta: 1.8,
            color: null,
            comment:
                "# Commentary: Black Move 85 (P8)\n\nBlack entered this position with a commanding +8.3-point lead and 91.7% win probability—a substantial cushion that left little room for White to slip back. With P8, Black increased that advantage to +8.1 points on the scoreboard and 93.5% win probability, a clean +1.8% swing that confirms the move's soundness. Though KataGo ranked P8 as the outright best move, its low policy prior (0.024) suggests it does not have the intuitive appeal of more natural-looking plays; in other words, it reads as a quiet, somewhat unconventional choice rather than a flashy tactical blow.\n\nThe move aims to solidify Black's claim on the right side, where the ownership map shows contested and lightly-favoring-Black territory around columns N–Q, rows 8–10. The principal variation pushes the game through the center (P9, L10, J11) and into the left-center region (H13, E8, E9), suggesting that P8 is less an immediate tactical strike and more a positional anchor—one that gives Black comfortable options to expand and manage the overall board balance while White scrambles to find compensation elsewhere.",
        },
        {
            turn: 86,
            winrate_delta: -2.2,
            color: null,
            comment:
                "# Commentary on Move 86 (White P9)\n\nWhite is in serious trouble: Black holds a commanding 91.5% win probability and leads by nearly 10 points even after this move. P9 is a weak choice — ranked only 11th by KataGo with a policy prior of just 0.003, meaning the neural network almost never considers it in similar positions. The move does slightly reduce Black's advantage (dropping the win rate by 2.2%), but it leaves White's position essentially unchanged.\n\nKataGo's top suggestion, J11, would have been transformative: it swings the entire game, shifting Black's win probability to just 6.7% and flipping the score lead to White by 7.2 points. The principal variation runs through J10, G11, and F10 — a sequence that appears to target the center and upper board, where multiple Black groups (particularly around H12–M12) sit in contested territory according to the ownership map. While the exact tactical sequence is complex, J11 clearly opens up White's central and left-side potential in a way that P9, anchored to White's already-secure right side, simply does not.",
        },
        {
            turn: 87,
            winrate_delta: -6.8,
            color: null,
            comment:
                "Black entered move 87 with a commanding position: an 91.8% win rate and a +10.1 point lead, suggesting the game was largely decided. Q9, however, was a notably conservative choice—ranked only 3rd among Black's options—and it cost real equity, dropping the win rate to 85.0% and the score lead to +8.5 points. The move plays into White's territory on the right side (ownership map shows local White advantage around -0.68), without clear compensation elsewhere on the board.\n\nKataGo's preferred move, L10, would have maintained Black's dominance by improving both the win rate to 92.2% and the score lead to +10.4 points. The principal variation suggests L10 targets the center and lower-middle region, where Black's scattered stones (at H10, K10, K9) can generate fighting chances and influence—a markedly different strategic direction from Q9's passive right-side approach. While the exact tactical justification is difficult to extract from position alone, the data is clear: Q9 allowed Black to slip backward in an already-winning game, whereas L10 would have tightened the vise.",
        },
        {
            turn: 89,
            winrate_delta: -24.3,
            color: null,
            comment:
                "# Commentary on Black Move 89 (R9)\n\nBlack was in a commanding position before this move: up by 8.3 points with an 84.5% win probability, effectively on track to convert a large advantage. However, R9 proved to be a costly error, collapsing both the win rate to 60.2% and the score lead to just +2.1 points — a stunning swing of 24.3 percentage points and 6.2 points of score in a single play. While R9 ranks as KataGo's 2nd choice (so not catastrophic), it lands on the right side where White already maintains local dominance (ownership ~−0.71), walking into an area where Black has little natural support.\n\nKataGo's top preference, L10, would have preserved Black's commanding advantage entirely (+8.4 points, 84.8% win rate) while keeping the fighting concentrated around the center—rows 10–13 in the K–L–M area, where the principal variation runs deep through J11, H13, and subsequent moves. The ownership map shows this central zone as contested or leaning Black, suggesting it was a more natural battleground for Black to dominate. R9, by contrast, invites White to activate its right-side strength, as the subsequent position demonstrates.",
        },
        {
            turn: 93,
            winrate_delta: -27.2,
            color: null,
            comment:
                "# Commentary on Black Move 93 (S9)\n\nBlack came into this move with a solid advantage—a 58.7% win rate and a +1.8 point lead—with significant strength along the upper side and contested ground throughout the rest of the board. The choice to play S9, however, was a serious mistake: the move doesn't appear in KataGo's top candidates at all, and it triggers a catastrophic swing of 27.2 percentage points in win rate, dropping Black from 58.7% to just 31.5% and flipping the score from +1.8 to –2.3 points against. S9 places Black's stone on the right edge, precisely where the ownership map shows White leaning strongest (local average around –0.66); the move appears to accomplish little while abandoning Black's initiative.\n\nKataGo's top suggestion, H13, offered a fundamentally different strategy: it would have improved the win rate to 59.7% (+2.0 point lead) and oriented Black's play toward the center and lower side, where the principal variation runs through J10, H8, and further fighting along the E, K, and M columns. The board shows Black has solid stones scattered through the center (E10, G14, M12–13), and H13 targets that region rather than passively extending on the perimeter—though the exact tactical sequence would need deeper calculation to fully justify why that specific territory is more valuable than what S9 attempts to secure.",
        },
        {
            turn: 95,
            winrate_delta: 0.3,
            color: null,
            comment:
                "# Commentary on Black Move 95 (Q13)\n\nBlack remains significantly behind, trailing by 2.2 points with only 32.1% winning chances—a precarious position in the endgame. Q13 was Black's second-best move according to KataGo and a natural-looking choice (high policy prior of 0.177), but it barely moved the needle, gaining just +0.3% winrate while leaving the score deficit unchanged. The suggested R7 was notably stronger, improving Black's position to 34.1% winrate and closing the score gap to –1.7 points; the principal variation suggests a sharp sequence along the right side and center (R7–R6–H13–J10), where Black appears to be fighting for better compensation. While the exact tactical payoff of R7 is difficult to pin down from the position alone, the data makes clear that it addresses the right-side contest more actively than Q13's quieter placement.",
        },
        {
            turn: 97,
            winrate_delta: -17.3,
            color: null,
            comment:
                "# Commentary on Black 97 (C4)\n\nBlack was already in serious trouble entering this move—down 2.7 points with only 28.1% winning chances—but C4 makes the situation dramatically worse. KataGo shows the move collapsing Black's position by 17.3% win rate and another 4.3 points of score loss in a single play, dropping to a near-hopeless 10.8% win probability. Critically, C4 wasn't even among KataGo's candidate moves, a red flag that usually signals a severe misjudgment.\n\nThe ownership map clarifies part of the problem: C4 sits in contested territory on the lower left (local ownership –0.61, leaning White), and playing here doesn't appear to address Black's real weaknesses or build on existing strength. In contrast, KataGo's top choice, H13, maintains Black's winning chances near 28.6% and keeps the score deficit to –2.5 points—nearly recovering what C4 threw away. The principal variation running through J10, C12, E15, and up the left side suggests H13 was aimed at activating play in the center and upper portions of the board, where Black holds firmer footing (the ownership map shows Black's strongest secured area around H15–H19). Without a clear tactical reason for C4's dramatic failure visible in the board position alone, this appears to be a straightforward choice of a lower-priority area when central play was urgent.",
        },
        {
            turn: 103,
            winrate_delta: 0.4,
            color: null,
            comment:
                "# Commentary: Black Move 103 (H13)\n\nBlack is in serious trouble, down nearly 9.3 points with only a 5.2% winning chance — this endgame is almost lost. H13 is the engine's top choice and a sensible move: it gains back 0.9 points on the score and improves Black's win probability slightly to 5.6%, which is meaningful in a desperate position. The move sits in contested central territory (ownership around +0.27), and the principal variation suggests Black is trying to create complications on the lower side and center by following H13 → J10 → G7 → J7, where there may be tactical skirmishes that could help chip away at White's lead. While H13 doesn't rescue the game, it keeps Black fighting in the areas where White's control is thinnest, rather than accepting a passive loss.",
        },
        {
            turn: 120,
            winrate_delta: 1.3,
            color: null,
            comment:
                "# Move 120 Commentary\n\nWhite is in a commanding position, leading by 12.6 points with a 95.8% win probability, but the move F5 represents a significant letdown. While F5 improves the score by 2.6 points and gains 1.3% win rate, it ranks only 12th among candidate moves and carries an extremely low policy prior (0.007), suggesting the neural net would almost never play here naturally. In contrast, KataGo's top suggestion J12 is transformative: it flips the game entirely, giving Black a 96.3% win probability and a +12.8 point lead—a swing of over 25 points in a single move. Looking at the board, J12 initiates a forcing sequence along the upper-left corridor (the PV continues H9, J6, D14, D12, B12) that exploits Black's existing strength in that region (shown by strong Black ownership on the upper and left sides), whereas F5, despite sitting in a locally favorable spot for White, leaves Black's winning strategy untouched and fails to disrupt the critical upper-side play where the game is actually being decided.",
        },
    ],
    annotated_sgf_content: "",
};
